### ISSUE TITLE
Inline js comments

### ISSUE THREAD

**Issue by widoz** [cferdinandi/html-minify#11]
Hi, seems that the inline js comments within scripts added into the html are creating problems. The code underneath the comment is commented too. All of the content. There is no way to strip the js comments?

**Comment by cferdinandi** [comment]
Per the docs, have you disabled inline JS minification in the settings?

**Comment by widoz** [comment]
No, no one ignore setting is enabled.

**Comment by cferdinandi** [comment]
Try that first then. Known bug, per the docs.

**Comment by widoz** [comment]
Hi, sorry me but enabling the **Ignore inline JavaScript** option the js will not be minified.

**Comment by cferdinandi** [comment]
That's right. But the rest of your HTML will be. You should minify your JS on your own end anyways.

**Comment by widoz** [comment]
Uhm, I don't think this is the best solution. Anyway thanks for your time. I'll try another way to minify the js.

**Comment by cferdinandi** [comment]
This plugin is not designed to minify JS. Well formed inline JS can be safely minified, but you'd be far better off using Uglify.js or something like that. The primary goal here is to minify HTML, which it does.

**Comment by cferdinandi** [comment]
Also, the docs clearly state in multiple places: "Inline JavaScript sometimes breaks when minified, so you may wish to exclude it from minification."

**Comment by widoz** [comment]
I understand that the plugin is not designed to minify the js, but this means I must minify my js even on my development version. The inline js may be used inside a php file, in that case will be problematic to maintain the code.

**Comment by cferdinandi** [comment]
I understand. Honestly, you should be avoiding large chunks of inline JS anyways, so I think the impact of excluding it from minification is minimal.
