### ISSUE TITLE
Link to settings page in plugin description broken.

### ISSUE THREAD

**Issue by michaeltorbert** [cferdinandi/html-minify#14]
It goes to page=html_minify_theme_options instead of page=html_minify_options

**Comment by cferdinandi** [comment]
Fixed with https://github.com/cferdinandi/html-minify/pull/15

**Comment by cferdinandi** [comment]
Thanks @michaeltorbert!

**Comment by michaeltorbert** [comment]
@cferdinandi You're very welcome. Cool plugin. I may have some more contributions later. ;)
