### ISSUE TITLE
JS compression when there is CDATA inline : update to make it work ;)

### ISSUE THREAD

**Issue by JibsouX** [cferdinandi/html-minify#4]
Now the plugin make site crash when there is a CDATA balise in the source code when we want to minify JS

there is a modification to do for make it work :
Add those line :
        $str = str_replace("//<![CDATA[",  '', $str);
        $str = str_replace("//]]>",  '', $str);

in 

```
protected function removeWhiteSpace($str) { ...
```

like that : 

```
protected function removeWhiteSpace($str)
{
    $str = str_replace("\t", ' ', $str);
    $str = str_replace("\n",  '', $str);
    $str = str_replace("\r",  '', $str);
    $str = str_replace("//<![CDATA[",  '', $str);
    $str = str_replace("//]]>",  '', $str);

    while (stristr($str, '  '))
    {
        $str = str_replace('  ', ' ', $str);
    }

    return $str;
```

By the way it will be a good thing to do : add a checkbox in admin to activate or not the result of the compression

protected function bottomComment($raw, $compressed) {
        $raw = strlen($raw);
        $compressed = strlen($compressed);
        $savings = ($raw-$compressed) / $raw \* 100;
        $savings = round($savings, 2);
        return '';
    }

$this->html .= "\n" . $this->bottomComment($html, $this->html);

**Comment by inoas** [comment]
> I hear you, but I also think it's best to promote proper coding practices rather than accommodating bad ones. If it's really breaking your code, you can always choose to omit JS from minification.

xhtml5-polyglot is proper coding practice as it has - aside a few edge cases like this - no downside but allows interaction with tools such XSL, XML Schema validation, MathML, SVG and whatnot.

p.s.: I am just writing my own minifier and got here by accident.
